name = "YOLO"
uuid = "af39948a-0e9f-11e9-2d1f-e71fbfcf41dd"
authors = ["Ian Butterworth <i.r.butterworth@gmail.com>", "Yavuz Faruk Bakman"]
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FreeTypeAbstraction = "663a7486-cb36-511b-a19d-713bb74d65c9"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
ImageDraw = "4381153b-2b60-58ae-a1ba-fd683676385f"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Knet = "1902f260-5fb4-5aff-8c31-6271790ab950"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
